services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql_server_airflow
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrongP@ssw0rd!"
      TZ: "America/Sao_Paulo"
    volumes:
      - ./cursos_sql_server:/var/opt/mssql
    restart: always
    networks:
      mssql_net:
        ipv4_address: 172.28.1.10

networks:
  mssql_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

volumes:
  cursos_sql_server:
