
services:
  oracle-xe:
    image: gvenzl/oracle-xe:latest
    container_name: oracle-xe
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: "123456"
      APP_USER: appuser
      APP_USER_PASSWORD: apppass123
      TZ: "America/Sao_Paulo"
    volumes:
      - ./oracle-volume:/opt/oracle/oradata
    networks:
      oracle_net:
        ipv4_address: 172.30.0.10
    restart: unless-stopped

networks:
  oracle_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
          gateway: 172.30.0.1

volumes:
  oracle-volume:

